[workspace]
members = ["cfg", "tdce"]
resolver = "2"

[workspace.dependencies]
bril-rs = { version = "0.1.0", path = "../bril-rs", features = [
  "ssa",
  "memory",
  "float",
  "speculate",
  "position",
] }
snafu = { version = "0.9.0" }
argh = { version = "0.1.19" }
indexmap = { version = "2.13.1" }
